#!/bin/sh
# Copyright 2008-2015 Dropbox, Inc.
#
# Environment script for the dropbox executable.
PAR=$(dirname "$(readlink -f "$0")")
OLD_LD_LIBRARY_PATH="$LD_LIBRARY_PATH"
export OLD_LD_LIBRARY_PATH
export QT_PLUGIN_PATH=
exec "$PAR"/dropbox "$@"
